# Generated by Django 5.2.5 on 2025-10-20 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0005_employee_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_latitude', models.FloatField()),
                ('check_in_longitude', models.FloatField()),
                ('check_in_image', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('distance_from_station', models.FloatField(blank=True, help_text='Distance in meters', null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.employee')),
            ],
            options={
                'ordering': ['-check_in_date'],
            },
        ),
    ]
