# Generated by Django 5.2.5 on 2025-10-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0003_remove_employee_role_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='attendance.station'),
        ),
    ]
