# Generated by Django 5.2.5 on 2025-10-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload employee profile picture', null=True, upload_to='employee_photos/'),
        ),
    ]
