# Generated by Django 5.2.5 on 2025-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_employeepayroll_basic_salary_and_more'),
        ('users', '0006_employee_bank_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.ManyToManyField(blank=True, help_text='Allowances applicable to this employee', related_name='employees', to='payroll.allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base salary of the employee', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='night_overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Night overtime rate per hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard overtime rate per hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekend_overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weekend overtime rate per hour', max_digits=10),
        ),
    ]
