# Generated by Django 5.2.5 on 2025-11-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_employee_bank_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_taxable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_statutory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye_band_1_limit', models.DecimalField(decimal_places=2, default=24000, max_digits=10)),
                ('paye_band_1_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('paye_band_2_limit', models.DecimalField(decimal_places=2, default=40667, max_digits=10)),
                ('paye_band_2_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('paye_band_3_rate', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('nssf_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('nssf_cap', models.DecimalField(decimal_places=2, default=2160.0, max_digits=10)),
                ('shif_rate', models.DecimalField(decimal_places=2, default=2.75, max_digits=5)),
                ('housing_levy_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=150.0, help_text='Default rate per overtime hour (KES)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Setting',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shif', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nssf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('housing_levy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
            options={
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.employeepayroll')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.employeepayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollperiod'),
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='users.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='payroll.payrollperiod')),
            ],
            options={
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeepayroll',
            unique_together={('employee', 'period')},
        ),
    ]
