# Generated by Django 5.2.5 on 2025-12-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('users', '0006_employee_bank_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeededuction',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='employeededuction',
            name='employee_payroll',
        ),
        migrations.AlterModelOptions(
            name='employeepayroll',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payrollsetting',
            options={},
        ),
        migrations.RenameField(
            model_name='payrollperiod',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='overtimerecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='housing_levy',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='nssf',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='shif',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='housing_levy_rate',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='nssf_cap',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='nssf_rate',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='overtime_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='payrollsetting',
            name='shif_rate',
        ),
        migrations.AddField(
            model_name='deduction',
            name='apply_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod'),
        ),
        migrations.CreateModel(
            name='EmployeeNonStatutoryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction', models.ForeignKey(limit_choices_to={'is_statutory': False}, on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_statutory_deductions', to='payroll.employeepayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollStatutoryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_deductions', to='payroll.employeepayroll')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeAllowance',
        ),
        migrations.DeleteModel(
            name='EmployeeDeduction',
        ),
        migrations.RemoveField(
            model_name='overtimerecord',
            name='date_created',
        ),
    ]
