# Generated by Django 5.2.5 on 2025-12-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_employeededuction_deduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayroll',
            name='overtime_pay',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='total_allowances',
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
                ('employee_payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.employeepayroll')),
            ],
        ),
    ]
