# Generated by Django 5.2.5 on 2025-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_employeepayroll_overtime_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayroll',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='overtimerecord',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='overtimerecord',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='standard_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='weekend_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
