# Generated by Django 5.2.5 on 2025-12-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_employeepayroll_basic_salary_and_more'),
        ('users', '0007_employee_allowances_employee_basic_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeallowance',
            name='employee_payroll',
        ),
        migrations.RemoveField(
            model_name='employeenonstatutorydeduction',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='employeenonstatutorydeduction',
            name='employee_payroll',
        ),
        migrations.RemoveField(
            model_name='overtimerecord',
            name='period',
        ),
        migrations.AddField(
            model_name='allowance',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_allowances', to='users.employee'),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='period_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='period_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='employeenonstatutorydeduction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_statutory_deductions', to='users.employee'),
        ),
        migrations.AddField(
            model_name='employeenonstatutorydeduction',
            name='period_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12),
        ),
        migrations.AddField(
            model_name='employeenonstatutorydeduction',
            name='period_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='period_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='period_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='employeeallowance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeenonstatutorydeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeenonstatutorydeduction',
            name='deduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction'),
        ),
        migrations.AlterField(
            model_name='overtimerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='users.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeStatutoryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12)),
                ('period_year', models.IntegerField(default=2025)),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statutory_deductions', to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_taxable', models.BooleanField(default=True)),
                ('period_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('period_year', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='users.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='PayrollStatutoryDeduction',
        ),
    ]
