# Generated by Django 5.2.5 on 2025-11-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='allocated_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
