# Generated by Django 5.2.5 on 2025-11-05 18:34

import django.db.models.deletion
import leave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavebalance_allocated_days_leavebalance_used_days'),
        ('users', '0006_employee_bank_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapprovalrecord',
            options={'ordering': ['step']},
        ),
        migrations.AlterModelOptions(
            name='leaveapprover',
            options={'ordering': ['step']},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='day_type',
        ),
        migrations.AddField(
            model_name='leaveapprovalrecord',
            name='step',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveapprover',
            name='step',
            field=models.PositiveIntegerField(blank=True, help_text='Approval order: 1=first, 2=second, etc.', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='current_step',
            field=models.PositiveIntegerField(default=1, help_text='Which approval step is active now'),
        ),
        migrations.AlterField(
            model_name='leaveapprovalrecord',
            name='action',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapprovalrecord',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='leave.leaverequest'),
        ),
        migrations.AlterField(
            model_name='leaveapprover',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_approvers', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document (e.g. medical or travel proof)', null=True, upload_to=leave.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
