# Generated by Django 5.2.5 on 2025-10-28 17:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='document_attachments',
            field=models.FileField(blank=True, null=True, upload_to='approval_docs/'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='rich_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Add detailed notes, images, or documents here.', null=True),
        ),
    ]
