# Generated by Django 5.2.5 on 2025-11-09 07:43

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalrecord_document_attachments_and_more'),
        ('users', '0006_employee_bank_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='The employee who should approve at this level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_approver', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='rich_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
