# Generated by Django 5.2.5 on 2025-11-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvalflow_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='rich_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
