# Generated by Django 5.2.5 on 2025-11-14 18:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_alter_approvalrecord_rich_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='rich_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
