# Generated by Django 5.2.5 on 2025-11-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_alter_approvalrecord_content_type_and_more'),
        ('users', '0006_employee_bank_account_number_employee_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='approvals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approvals.approvalrecord')),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee')),
            ],
        ),
    ]
