# Generated by Django 5.2.5 on 2025-11-16 07:40

import approvals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_approvalattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalattachment',
            name='file',
            field=models.FileField(upload_to=approvals.models.approval_attachment_path),
        ),
    ]
