# Generated by Django 5.2.5 on 2025-11-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_alter_approvalattachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrecord',
            name='document_attachments',
        ),
    ]
